### Home
GET http://localhost:3000/

### Notes
GET http://localhost:3000/notes

### Note by ID
GET http://localhost:3000/notes/1

### Create Note
POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "Belajar Node.js"
}

### Update Note
PUT http://localhost:3000/notes/1
Content-Type: application/json

{
    "title": "Belajar Node.js Updated"
}

### Delete Note
DELETE http://localhost:3000/notes/1





